# Generated by Django 4.0.1 on 2022-06-07 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newsstory_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsstory',
            old_name='img',
            new_name='image_url',
        ),
    ]
